// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: materials/material_message.proto

package materials

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	generic "lms-material-service/pb/generic"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaterialService_List_FullMethodName   = "/materials.MaterialService/List"
	MaterialService_Get_FullMethodName    = "/materials.MaterialService/Get"
	MaterialService_Create_FullMethodName = "/materials.MaterialService/Create"
	MaterialService_Update_FullMethodName = "/materials.MaterialService/Update"
	MaterialService_Delete_FullMethodName = "/materials.MaterialService/Delete"
)

// MaterialServiceClient is the client API for MaterialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaterialServiceClient interface {
	List(ctx context.Context, in *MaterialListInput, opts ...grpc.CallOption) (*MaterialList, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Material, error)
	Create(ctx context.Context, in *MaterialInput, opts ...grpc.CallOption) (*Material, error)
	Update(ctx context.Context, in *Material, opts ...grpc.CallOption) (*Material, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type materialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaterialServiceClient(cc grpc.ClientConnInterface) MaterialServiceClient {
	return &materialServiceClient{cc}
}

func (c *materialServiceClient) List(ctx context.Context, in *MaterialListInput, opts ...grpc.CallOption) (*MaterialList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterialList)
	err := c.cc.Invoke(ctx, MaterialService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Material, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Material)
	err := c.cc.Invoke(ctx, MaterialService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialServiceClient) Create(ctx context.Context, in *MaterialInput, opts ...grpc.CallOption) (*Material, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Material)
	err := c.cc.Invoke(ctx, MaterialService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialServiceClient) Update(ctx context.Context, in *Material, opts ...grpc.CallOption) (*Material, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Material)
	err := c.cc.Invoke(ctx, MaterialService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, MaterialService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaterialServiceServer is the server API for MaterialService service.
// All implementations should embed UnimplementedMaterialServiceServer
// for forward compatibility.
type MaterialServiceServer interface {
	List(context.Context, *MaterialListInput) (*MaterialList, error)
	Get(context.Context, *generic.Id) (*Material, error)
	Create(context.Context, *MaterialInput) (*Material, error)
	Update(context.Context, *Material) (*Material, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedMaterialServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaterialServiceServer struct{}

func (UnimplementedMaterialServiceServer) List(context.Context, *MaterialListInput) (*MaterialList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMaterialServiceServer) Get(context.Context, *generic.Id) (*Material, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMaterialServiceServer) Create(context.Context, *MaterialInput) (*Material, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMaterialServiceServer) Update(context.Context, *Material) (*Material, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMaterialServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMaterialServiceServer) testEmbeddedByValue() {}

// UnsafeMaterialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaterialServiceServer will
// result in compilation errors.
type UnsafeMaterialServiceServer interface {
	mustEmbedUnimplementedMaterialServiceServer()
}

func RegisterMaterialServiceServer(s grpc.ServiceRegistrar, srv MaterialServiceServer) {
	// If the following call panics, it indicates UnimplementedMaterialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaterialService_ServiceDesc, srv)
}

func _MaterialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterialListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaterialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaterialService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaterialServiceServer).List(ctx, req.(*MaterialListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaterialService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaterialServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaterialService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaterialServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaterialService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterialInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaterialServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaterialService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaterialServiceServer).Create(ctx, req.(*MaterialInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaterialService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Material)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaterialServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaterialService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaterialServiceServer).Update(ctx, req.(*Material))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaterialService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaterialServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaterialService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaterialServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// MaterialService_ServiceDesc is the grpc.ServiceDesc for MaterialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaterialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "materials.MaterialService",
	HandlerType: (*MaterialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _MaterialService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MaterialService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _MaterialService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MaterialService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MaterialService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "materials/material_message.proto",
}

const (
	StudentMaterialService_List_FullMethodName           = "/materials.StudentMaterialService/List"
	StudentMaterialService_Create_FullMethodName         = "/materials.StudentMaterialService/Create"
	StudentMaterialService_UpdateProgress_FullMethodName = "/materials.StudentMaterialService/UpdateProgress"
	StudentMaterialService_Delete_FullMethodName         = "/materials.StudentMaterialService/Delete"
)

// StudentMaterialServiceClient is the client API for StudentMaterialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentMaterialServiceClient interface {
	List(ctx context.Context, in *StudentMaterialListInput, opts ...grpc.CallOption) (*StudentMaterialList, error)
	Create(ctx context.Context, in *StudentMaterialInput, opts ...grpc.CallOption) (*StudentMaterial, error)
	UpdateProgress(ctx context.Context, in *UpdateProgressInput, opts ...grpc.CallOption) (*StudentMaterial, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type studentMaterialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentMaterialServiceClient(cc grpc.ClientConnInterface) StudentMaterialServiceClient {
	return &studentMaterialServiceClient{cc}
}

func (c *studentMaterialServiceClient) List(ctx context.Context, in *StudentMaterialListInput, opts ...grpc.CallOption) (*StudentMaterialList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMaterialList)
	err := c.cc.Invoke(ctx, StudentMaterialService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentMaterialServiceClient) Create(ctx context.Context, in *StudentMaterialInput, opts ...grpc.CallOption) (*StudentMaterial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMaterial)
	err := c.cc.Invoke(ctx, StudentMaterialService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentMaterialServiceClient) UpdateProgress(ctx context.Context, in *UpdateProgressInput, opts ...grpc.CallOption) (*StudentMaterial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMaterial)
	err := c.cc.Invoke(ctx, StudentMaterialService_UpdateProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentMaterialServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, StudentMaterialService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentMaterialServiceServer is the server API for StudentMaterialService service.
// All implementations should embed UnimplementedStudentMaterialServiceServer
// for forward compatibility.
type StudentMaterialServiceServer interface {
	List(context.Context, *StudentMaterialListInput) (*StudentMaterialList, error)
	Create(context.Context, *StudentMaterialInput) (*StudentMaterial, error)
	UpdateProgress(context.Context, *UpdateProgressInput) (*StudentMaterial, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedStudentMaterialServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudentMaterialServiceServer struct{}

func (UnimplementedStudentMaterialServiceServer) List(context.Context, *StudentMaterialListInput) (*StudentMaterialList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStudentMaterialServiceServer) Create(context.Context, *StudentMaterialInput) (*StudentMaterial, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStudentMaterialServiceServer) UpdateProgress(context.Context, *UpdateProgressInput) (*StudentMaterial, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgress not implemented")
}
func (UnimplementedStudentMaterialServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStudentMaterialServiceServer) testEmbeddedByValue() {}

// UnsafeStudentMaterialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentMaterialServiceServer will
// result in compilation errors.
type UnsafeStudentMaterialServiceServer interface {
	mustEmbedUnimplementedStudentMaterialServiceServer()
}

func RegisterStudentMaterialServiceServer(s grpc.ServiceRegistrar, srv StudentMaterialServiceServer) {
	// If the following call panics, it indicates UnimplementedStudentMaterialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudentMaterialService_ServiceDesc, srv)
}

func _StudentMaterialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentMaterialListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentMaterialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentMaterialService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentMaterialServiceServer).List(ctx, req.(*StudentMaterialListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentMaterialService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentMaterialInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentMaterialServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentMaterialService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentMaterialServiceServer).Create(ctx, req.(*StudentMaterialInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentMaterialService_UpdateProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgressInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentMaterialServiceServer).UpdateProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentMaterialService_UpdateProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentMaterialServiceServer).UpdateProgress(ctx, req.(*UpdateProgressInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentMaterialService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentMaterialServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentMaterialService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentMaterialServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentMaterialService_ServiceDesc is the grpc.ServiceDesc for StudentMaterialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentMaterialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "materials.StudentMaterialService",
	HandlerType: (*StudentMaterialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _StudentMaterialService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StudentMaterialService_Create_Handler,
		},
		{
			MethodName: "UpdateProgress",
			Handler:    _StudentMaterialService_UpdateProgress_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StudentMaterialService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "materials/material_message.proto",
}
