// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: materials/material_message.proto

package materials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-material-service/pb/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Material struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	FileType       string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	StorageId      string                 `protobuf:"bytes,7,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source         string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_materials_material_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{0}
}

func (x *Material) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Material) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Material) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *Material) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Material) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Material) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Material) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *Material) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Material) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Material) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Material) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MaterialList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*Material            `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialList) Reset() {
	*x = MaterialList{}
	mi := &file_materials_material_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialList) ProtoMessage() {}

func (x *MaterialList) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialList.ProtoReflect.Descriptor instead.
func (*MaterialList) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{1}
}

func (x *MaterialList) GetMaterials() []*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *MaterialList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MaterialListInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MaterialListInput) Reset() {
	*x = MaterialListInput{}
	mi := &file_materials_material_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialListInput) ProtoMessage() {}

func (x *MaterialListInput) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialListInput.ProtoReflect.Descriptor instead.
func (*MaterialListInput) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{2}
}

func (x *MaterialListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *MaterialListInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

type MaterialInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId string                 `protobuf:"bytes,1,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,2,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	FileType       string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Name           string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	StorageId      string                 `protobuf:"bytes,6,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source         string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MaterialInput) Reset() {
	*x = MaterialInput{}
	mi := &file_materials_material_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialInput) ProtoMessage() {}

func (x *MaterialInput) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialInput.ProtoReflect.Descriptor instead.
func (*MaterialInput) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{3}
}

func (x *MaterialInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *MaterialInput) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *MaterialInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MaterialInput) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *MaterialInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MaterialInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *MaterialInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type StudentMaterial struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialId         string                 `protobuf:"bytes,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	StudentId          string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	IsDownloaded       bool                   `protobuf:"varint,4,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	ProgressDownloaded int32                  `protobuf:"varint,5,opt,name=progress_downloaded,json=progressDownloaded,proto3" json:"progress_downloaded,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy          string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StudentMaterial) Reset() {
	*x = StudentMaterial{}
	mi := &file_materials_material_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMaterial) ProtoMessage() {}

func (x *StudentMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMaterial.ProtoReflect.Descriptor instead.
func (*StudentMaterial) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{4}
}

func (x *StudentMaterial) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentMaterial) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *StudentMaterial) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentMaterial) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

func (x *StudentMaterial) GetProgressDownloaded() int32 {
	if x != nil {
		return x.ProgressDownloaded
	}
	return 0
}

func (x *StudentMaterial) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StudentMaterial) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type StudentMaterialList struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StudentMaterials []*StudentMaterial     `protobuf:"bytes,1,rep,name=student_materials,json=studentMaterials,proto3" json:"student_materials,omitempty"`
	Count            uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudentMaterialList) Reset() {
	*x = StudentMaterialList{}
	mi := &file_materials_material_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMaterialList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMaterialList) ProtoMessage() {}

func (x *StudentMaterialList) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMaterialList.ProtoReflect.Descriptor instead.
func (*StudentMaterialList) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{5}
}

func (x *StudentMaterialList) GetStudentMaterials() []*StudentMaterial {
	if x != nil {
		return x.StudentMaterials
	}
	return nil
}

func (x *StudentMaterialList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StudentMaterialListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	MaterialId    string                 `protobuf:"bytes,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentMaterialListInput) Reset() {
	*x = StudentMaterialListInput{}
	mi := &file_materials_material_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMaterialListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMaterialListInput) ProtoMessage() {}

func (x *StudentMaterialListInput) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMaterialListInput.ProtoReflect.Descriptor instead.
func (*StudentMaterialListInput) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{6}
}

func (x *StudentMaterialListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *StudentMaterialListInput) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type StudentMaterialInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentMaterialInput) Reset() {
	*x = StudentMaterialInput{}
	mi := &file_materials_material_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMaterialInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMaterialInput) ProtoMessage() {}

func (x *StudentMaterialInput) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMaterialInput.ProtoReflect.Descriptor instead.
func (*StudentMaterialInput) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{7}
}

func (x *StudentMaterialInput) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *StudentMaterialInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type UpdateProgressInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDownloaded       bool                   `protobuf:"varint,2,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	ProgressDownloaded int32                  `protobuf:"varint,3,opt,name=progress_downloaded,json=progressDownloaded,proto3" json:"progress_downloaded,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProgressInput) Reset() {
	*x = UpdateProgressInput{}
	mi := &file_materials_material_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressInput) ProtoMessage() {}

func (x *UpdateProgressInput) ProtoReflect() protoreflect.Message {
	mi := &file_materials_material_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressInput.ProtoReflect.Descriptor instead.
func (*UpdateProgressInput) Descriptor() ([]byte, []int) {
	return file_materials_material_message_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProgressInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProgressInput) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

func (x *UpdateProgressInput) GetProgressDownloaded() int32 {
	if x != nil {
		return x.ProgressDownloaded
	}
	return 0
}

var File_materials_material_message_proto protoreflect.FileDescriptor

const file_materials_material_message_proto_rawDesc = "" +
	"\n" +
	" materials/material_message.proto\x12\tmaterials\x1a\x1dgeneric/generic_message.proto\"\xc7\x02\n" +
	"\bMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"storage_id\x18\a \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"W\n" +
	"\fMaterialList\x121\n" +
	"\tmaterials\x18\x01 \x03(\v2\x13.materials.MaterialR\tmaterials\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x80\x01\n" +
	"\x11MaterialListInput\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.lms_material_services.PaginationR\n" +
	"pagination\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\"\xdf\x01\n" +
	"\rMaterialInput\x12(\n" +
	"\x10subject_class_id\x18\x01 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x02 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x06 \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"\xf5\x01\n" +
	"\x0fStudentMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\tR\n" +
	"materialId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12#\n" +
	"\ris_downloaded\x18\x04 \x01(\bR\fisDownloaded\x12/\n" +
	"\x13progress_downloaded\x18\x05 \x01(\x05R\x12progressDownloaded\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\"t\n" +
	"\x13StudentMaterialList\x12G\n" +
	"\x11student_materials\x18\x01 \x03(\v2\x1a.materials.StudentMaterialR\x10studentMaterials\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"~\n" +
	"\x18StudentMaterialListInput\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.lms_material_services.PaginationR\n" +
	"pagination\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\tR\n" +
	"materialId\"V\n" +
	"\x14StudentMaterialInput\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"{\n" +
	"\x13UpdateProgressInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\ris_downloaded\x18\x02 \x01(\bR\fisDownloaded\x12/\n" +
	"\x13progress_downloaded\x18\x03 \x01(\x05R\x12progressDownloaded2\xbd\x02\n" +
	"\x0fMaterialService\x12=\n" +
	"\x04List\x12\x1c.materials.MaterialListInput\x1a\x17.materials.MaterialList\x125\n" +
	"\x03Get\x12\x19.lms_material_services.Id\x1a\x13.materials.Material\x127\n" +
	"\x06Create\x12\x18.materials.MaterialInput\x1a\x13.materials.Material\x122\n" +
	"\x06Update\x12\x13.materials.Material\x1a\x13.materials.Material\x12G\n" +
	"\x06Delete\x12\x19.lms_material_services.Id\x1a\".lms_material_services.BoolMessage2\xc3\x02\n" +
	"\x16StudentMaterialService\x12K\n" +
	"\x04List\x12#.materials.StudentMaterialListInput\x1a\x1e.materials.StudentMaterialList\x12E\n" +
	"\x06Create\x12\x1f.materials.StudentMaterialInput\x1a\x1a.materials.StudentMaterial\x12L\n" +
	"\x0eUpdateProgress\x12\x1e.materials.UpdateProgressInput\x1a\x1a.materials.StudentMaterial\x12G\n" +
	"\x06Delete\x12\x19.lms_material_services.Id\x1a\".lms_material_services.BoolMessageB-Z+lms-material-service/pb/materials;materialsb\x06proto3"

var (
	file_materials_material_message_proto_rawDescOnce sync.Once
	file_materials_material_message_proto_rawDescData []byte
)

func file_materials_material_message_proto_rawDescGZIP() []byte {
	file_materials_material_message_proto_rawDescOnce.Do(func() {
		file_materials_material_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_materials_material_message_proto_rawDesc), len(file_materials_material_message_proto_rawDesc)))
	})
	return file_materials_material_message_proto_rawDescData
}

var file_materials_material_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_materials_material_message_proto_goTypes = []any{
	(*Material)(nil),                 // 0: materials.Material
	(*MaterialList)(nil),             // 1: materials.MaterialList
	(*MaterialListInput)(nil),        // 2: materials.MaterialListInput
	(*MaterialInput)(nil),            // 3: materials.MaterialInput
	(*StudentMaterial)(nil),          // 4: materials.StudentMaterial
	(*StudentMaterialList)(nil),      // 5: materials.StudentMaterialList
	(*StudentMaterialListInput)(nil), // 6: materials.StudentMaterialListInput
	(*StudentMaterialInput)(nil),     // 7: materials.StudentMaterialInput
	(*UpdateProgressInput)(nil),      // 8: materials.UpdateProgressInput
	(*generic.Pagination)(nil),       // 9: lms_material_services.Pagination
	(*generic.Id)(nil),               // 10: lms_material_services.Id
	(*generic.BoolMessage)(nil),      // 11: lms_material_services.BoolMessage
}
var file_materials_material_message_proto_depIdxs = []int32{
	0,  // 0: materials.MaterialList.materials:type_name -> materials.Material
	9,  // 1: materials.MaterialListInput.pagination:type_name -> lms_material_services.Pagination
	4,  // 2: materials.StudentMaterialList.student_materials:type_name -> materials.StudentMaterial
	9,  // 3: materials.StudentMaterialListInput.pagination:type_name -> lms_material_services.Pagination
	2,  // 4: materials.MaterialService.List:input_type -> materials.MaterialListInput
	10, // 5: materials.MaterialService.Get:input_type -> lms_material_services.Id
	3,  // 6: materials.MaterialService.Create:input_type -> materials.MaterialInput
	0,  // 7: materials.MaterialService.Update:input_type -> materials.Material
	10, // 8: materials.MaterialService.Delete:input_type -> lms_material_services.Id
	6,  // 9: materials.StudentMaterialService.List:input_type -> materials.StudentMaterialListInput
	7,  // 10: materials.StudentMaterialService.Create:input_type -> materials.StudentMaterialInput
	8,  // 11: materials.StudentMaterialService.UpdateProgress:input_type -> materials.UpdateProgressInput
	10, // 12: materials.StudentMaterialService.Delete:input_type -> lms_material_services.Id
	1,  // 13: materials.MaterialService.List:output_type -> materials.MaterialList
	0,  // 14: materials.MaterialService.Get:output_type -> materials.Material
	0,  // 15: materials.MaterialService.Create:output_type -> materials.Material
	0,  // 16: materials.MaterialService.Update:output_type -> materials.Material
	11, // 17: materials.MaterialService.Delete:output_type -> lms_material_services.BoolMessage
	5,  // 18: materials.StudentMaterialService.List:output_type -> materials.StudentMaterialList
	4,  // 19: materials.StudentMaterialService.Create:output_type -> materials.StudentMaterial
	4,  // 20: materials.StudentMaterialService.UpdateProgress:output_type -> materials.StudentMaterial
	11, // 21: materials.StudentMaterialService.Delete:output_type -> lms_material_services.BoolMessage
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_materials_material_message_proto_init() }
func file_materials_material_message_proto_init() {
	if File_materials_material_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_materials_material_message_proto_rawDesc), len(file_materials_material_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_materials_material_message_proto_goTypes,
		DependencyIndexes: file_materials_material_message_proto_depIdxs,
		MessageInfos:      file_materials_material_message_proto_msgTypes,
	}.Build()
	File_materials_material_message_proto = out.File
	file_materials_material_message_proto_goTypes = nil
	file_materials_material_message_proto_depIdxs = nil
}
